name: Sync Fork

on:
  schedule:
    - cron: "0 6 * * *"  # Runs at 11:00 PM EST (4:00 AM UTC) every day

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/n8n-io/n8n.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
