name: Sync Fork

on:
  schedule:
    - cron: "0 4 * * *"  # Runs at 11:00 PM EST (4:00 AM UTC) every day
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/n8n-io/n8n.git
          git fetch upstream
          git checkout master
          git merge upstream/main
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
